apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: test1
spec:
  #Since new version of api this signerName is requied
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 600
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZUQ0NBVDBDQVFBd0VERU9NQXdHQTFVRUF3d0ZkR1Z6ZERFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFEbk9YQUdVeHFDa3J5Z21sS0FqU1VnbmVLSTFxRlA0cXYrV2hHOFJGblRWSDRwCnhYNURqaGZSUEpwL1ZrKzIwbVgzWDBLQTdMcXFKcWwzUU5kU0lmRm9HTjJzL2d4dVJTWHZ5NHJTNnlqelJoNUoKRlJGblpyVVlxQmcxMG5JT284eEgycDhNcVRHUmhNNzJrMCtVWVg5Vldla0hGVFVNY3J2TWllbmwwQ1ZMQzVuRwpBcnNxSU8vOXc3cnVGOE5KTllnNVF5ejRIb2NzUFEyOUpPWHpHb3o5RFYxSXZBNHl2SXN4Tjd1WFZ3WVZDMHBiCkdtWVEyTkpnTTgxVTdOTVBtTStxU056T1VJQUVSKzZiNjF0WjBsV1UxbXJjWnhQRFRSUlMrSWtaWFJ5NVI4VnUKbHBRb1hvWndLcmovWTdENHdUQVFJdlBYZlF2c1gyT2VsQzhuLzFJMUFnTUJBQUdnQURBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFtU0pmanpPVHhiQzNJN29XUEdWZXZ4RzlxM3VHaU0razJmb1hqTGprdlhMRzlybEk0U1BNCjR0aEZDMUZlZnNyYUdMb0RkM2g1bXZ1MEsxWTJIOW1ZYStZSGZEbjUvbWw4R0tBWnVGYW9oM0w2REMwRzBmdHUKWWFrQ0lPNkxTMDltYUtIZU9LcGY5VXRrQ3dRT081b1lQbWJDUjI2QitxY2ZEWVU1U1NNTEhlZXp2V0dUSXl2ZQp5VnRyclBkOWtvQ3hYdUhINlhOdlFTS3Jua0dSQWI5dWJ3L2RyYmxIWXl3Z1ZNRVJtRzlHd1FrT2NRZ2JtdzJFClVSUEJoaERZUWwzQVFyUFJ6cFJVQUF0R3ZTaEdhTmF6RjhrTUhiUmh3WEY1aU04b0orRStRREZjMTJEVXBjZS8KbGFGL2E5RU9hYlM4K3JpZXI1WXpXVWRwVzJjWjU3KzdhUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=